# Limpeza e Tratamento de Dados

Notebook responsável pela limpeza, padronização e transformação da base bruta de comportamento de compra de clientes.

**Entrada:** `data/raw/customer_shopping_behavior.csv`  
**Saída:** `data/processed/customer_shopping_behavior_clean.csv`

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'../data/raw/customer_shopping_behavior.csv', sep=',')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
# Informações gerais do DF
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [4]:
# Estatísticas resumidas das colunas numéricas e categóricas do DF
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
# Valores ausentes em cada colunas
df.isna().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

### Tratamento de Valores Ausentes — `review_rating`

**Estratégia:** imputação por grupo, utilizando a mediana de `review_rating` calculada individualmente para cada `category`.

**Justificativa:** decidi pela imputação por agrupamento, pois não assume homogeneidade entre subgrupos da base. Ao contrário da imputação global, que aplica uma única estatística a todos os registros. Essa abordagem preserva eventuais diferenças de distribuição entre categorias, sem custo adicional relevante de implementação.

In [6]:
# Imputando os valores ausentes de avaliações pela mediana de cada categoria
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.mean()))

In [7]:
# Verificando novamente se ainda tem valores ausentes na coluna 'Review Rating'
df['Review Rating'].isna().sum()

np.int64(0)

In [8]:
# Padronizando colunas no formato snake_case:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

### Segmentação de Clientes por Faixa Etária — `age_group`

**Estratégia:** divisão da variável `age` em 4 grupos utilizando `pd.qcut` (segmentação por quantil).

**Justificativa:** `qcut` particiona os dados em grupos de tamanho aproximadamente igual, com base na distribuição real da variável — ao contrário de `cut`, que utiliza intervalos fixos e arbitrários. Essa escolha garante que cada segmento seja estatisticamente representativo da base, refletindo a distribuição observada em vez de faixas etárias pré-definidas.

In [10]:
# Agrupando os clietes em 4 faixas etárias
labels = ['Young Adult', 'Adult', 'Middle-Agged', 'Senior']

# Convertendo as idades em dados categóricos e criando 4 grupos de tamanho iguais com base na distrbuição de dados
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [11]:
df[['age_group', 'age']].head(10)

      age_group  age
0  Middle-Agged   55
1   Young Adult   19
2  Middle-Agged   50
3   Young Adult   21
4  Middle-Agged   45
5  Middle-Agged   46
6        Senior   63
7   Young Adult   27
8   Young Adult   26
9  Middle-Agged   57

### Conversão de Frequência de Compra — `purchase_frequency_days`

**Estratégia:** mapeamento dos rótulos textuais de `frequency_of_purchases` (ex: "Fortnightly", "Monthly") para valores numéricos em dias.

**Justificativa:** a coluna original é categórica e não permite operações quantitativas diretas. A conversão para dias viabiliza análises como correlação e agregações estatísticas sobre o comportamento de recorrência de compra. Os valores atribuídos seguem o significado padrão de cada termo em inglês.

In [12]:
# Dicionária que associa 'frequency_of_purchases' (str) com números de dias correspondentes
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

# Criando uma coluna para frequência de compras por dia trasnformando em valores numéricos
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [13]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

### Verificação de Redundância — `discount_applied` x `promo_code_used`

**Estratégia:** comparação direta entre as colunas `discount_applied` e `promo_code_used` para identificar se carregam a mesma informação.

**Justificativa:** manter colunas redundantes aumenta a dimensionalidade da base sem agregar informação nova, além de poder introduzir ambiguidade em análises futuras. A comparação confirmou equivalência total entre as colunas.

In [14]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [15]:
# Verificando redundancia das colunas 'discount_applied' e 'promo_code_used'
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [16]:
# Removendo a coluna de código promocional usado
df = df.drop('promo_code_used', axis=1)

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

### Exportação do Dataset Tratado

**Estratégia:** exportação do DataFrame limpo para `data/processed/customer_shopping_behavior_clean.csv`.

**Justificativa:** manter dado bruto (`data/raw/`) e dado tratado (`data/processed/`) em diretórios separados preserva a rastreabilidade do pipeline e permite reprocessar os dados a partir da fonte original, se necessário.

In [18]:
# Salvando o DataFrame após a limpeza dos dados
df.to_csv(r"../data/processed/customer_shopping_behavior_clean.csv", sep=",", index=False)

In [ ]:
# Rastreamento das versões das bibliotecas usadas
%load_ext watermark
%watermark -v -p pandas